### ISSUE TITLE
Doc Page 404

### ISSUE THREAD

**Issue by Reapor-Yurnero** [gtfierro/ref-schema#7]
doc page no longer works for some reason.

**Comment by ghubrakesh** [comment]
doc page is works. It just that the website "docs.brickschema.org" appears to have an SSL/TLS certificate issued by Let's Encrypt, which is a certificate authority that provides free SSL/TLS certificates. However, the warning indicates that there might be issues with the certificate configuration:

**Comment by gtfierro** [comment]
It was actually down! You must have it cached, @ghubrakesh ?

I've fixed the site and it is accessible and has functional certs
